plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrains.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.hilt.plugin)
    alias(libs.plugins.ksp)
}

android {
    namespace 'com.basepos.pos.dspread'
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    //Hilt
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    //TIMBER
    implementation libs.timber

    //JPOS
    implementation libs.jpos

    coreLibraryDesugaring(libs.desugar.jdk.libs)

    implementation project(":Pos-Common")
    api project(":Dspread-Pos-Sdk")
    api project(":Dspread-Print-Sdk")
}