plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrains.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.hilt.plugin)
    alias(libs.plugins.ksp)
}

android {
    namespace 'com.basepos.pos.host'
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    //Hilt
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    //Room
    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler

    //TIMBER
    implementation libs.timber

    //JPOS
    implementation libs.jpos

    //Retrofit
    implementation libs.retrofit
    implementation libs.gsonConverter
    implementation libs.scalarsConverter
    implementation libs.okhttpLogger

    coreLibraryDesugaring(libs.desugar.jdk.libs)

    implementation project(":Pos-Common")
}